/**
 * This file was generated by Winstanley's Computer Science Department. 
 * The appropriate copyright license applies.
**/

import javax.swing.*;
import java.awt.GridLayout;

public class MyTabbedGUI {
    JFrame myWindow = new JFrame("Tabbed Program");
    
    /* Declare five panels */
    JPanel myFirstPanel = new JPanel(null);
    JPanel mySecondPanel = new JPanel(null);
    JPanel myThirdPanel = new JPanel(null);
    JPanel myFourthPanel = new JPanel(null);
    JPanel myFifthPanel = new JPanel(null);
    
    /* Create a corresponding Label to welcome each panel */
    JLabel lblForPanelOne = new JLabel ("Welcome to Panel One");
    JLabel lblForPanelTwo = new JLabel ("Welcome to Panel Two");
    JLabel lblForPanelThree = new JLabel ("Welcome to Panel Three");
    JLabel lblForPanelFour = new JLabel ("Welcome to Panel Four");
    JLabel lblForPanelFive = new JLabel ("Welcome to Panel Five");
    
    JTabbedPane myTabs = new JTabbedPane();
    
    public void buildMyTabbedGUI() {
        
        myWindow.setSize(500, 400);
        myWindow.setLocation(200, 200);
        myWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myWindow.setLayout(new GridLayout(1, 1)); // Change JFrame layout to a grid
        
        /* Generate 5 Panels */
        createPanelOne();
        myTabs.addTab("Panel One", myFirstPanel);

        createPanelTwo();
        myTabs.addTab("Panel Two", mySecondPanel);

        createPanelThree();
        myTabs.addTab("Panel Three", myThirdPanel);

        createPanelFour();
        myTabs.addTab("Panel Four", myFourthPanel);
        
        createPanelFive();
        myTabs.addTab("Panel Five", myFifthPanel);
        
        /* Add the tabs to the window */
        myWindow.add(myTabs);
        myWindow.setVisible(true);
    };
    
    /* Generate each Panel and add the label */
    public void createPanelOne() {   
        
        lblForPanelOne.setSize(200, 40);
        lblForPanelOne.setLocation(5, 0);
        myFirstPanel.add(lblForPanelOne);
        
    };
    
    public void createPanelTwo() {   
        
        lblForPanelTwo.setSize(200, 40);
        lblForPanelTwo.setLocation(5, 0);
        mySecondPanel.add(lblForPanelTwo);
        
    };
    
    public void createPanelThree() {   
        
        lblForPanelThree.setSize(200, 40);
        lblForPanelThree.setLocation(5, 0);
        myThirdPanel.add(lblForPanelThree);
        
    };
    
    public void createPanelFour() {   
        
        lblForPanelFour.setSize(200, 40);
        lblForPanelFour.setLocation(5, 0);
        myFourthPanel.add(lblForPanelFour);
        
    };
    
    public void createPanelFive() {   
        
        lblForPanelFive.setSize(200, 40);
        lblForPanelFive.setLocation(5, 0);
        myFifthPanel.add(lblForPanelFive);
        
    };
    
    
    public static void main(String[] args) {
        MyTabbedGUI mtg = new MyTabbedGUI();
        mtg.buildMyTabbedGUI();
    };
};
